INSERT INTO meal (name, fiber_amount) VALUES ('Pea & Spinach Carbonara', 8.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Brussels sprouts salad with crunchy chikpeas', 13.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Hearty chickpea & spinach stew', 13.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Butternut squash alfredo with chicken & spinach', 11.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Roasted pork tenderloin with vegetables & quinoa', 8.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Roasted root veggies & greens over spiced lentils', 14.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Spaghetti squash & chicken with avocado pesto', 8.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Creamy blueberry-pecan overnight oatmeal', 6.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Kale salad with quinoa & chicken', 4.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Vegetarian black bean & quinoa burrito bowl', 12.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Apple cinnamon chia pudding', 10.0);
INSERT INTO meal (name, fiber_amount) VALUES ('Baked banana-nut oatmeal cups', 3.0);
INSERT INTO meal (name, fiber_amount) VALUES ('1 cup of blackberries', 7.0);
INSERT INTO meal (name, fiber_amount) VALUES ('1 medium apple', 3.0);
INSERT INTO meal (name, fiber_amount) VALUES ('2oz of almonds', 7.0);
INSERT INTO meal (name, fiber_amount) VALUES ('kiwi', 3.0);
INSERT INTO meal (name, fiber_amount) VALUES ('pear', 6.0);
INSERT INTO meal (name, fiber_amount) VALUES ('banana', 3.0);
INSERT INTO meal (name, fiber_amount) VALUES ('avocado toast', 11.0);
INSERT INTO meal (name, fiber_amount) VALUES ('sweet potato fries', 4.0);
